---
name: CI

"on":
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: YAML Lint
        uses: ibiqlik/action-yamllint@v3.1.0
        with:
          file_or_dir: "blue-green/values.yaml"
